execute pathogen#infect()
call pathogen#helptags()

filetype plugin indent on
set encoding=utf-8

" syntax highlighting
syntax on

" set leader to space
let mapleader = "\<Space>"

" to enable airline from start
set laststatus=2
let g:airline_theme='solarized'

" From sensible vim
set ruler
set backspace=indent,eol,start

set autoindent " preserve indent level on newlines
set tabstop=2 " a tab is two spaces
set shiftwidth=2 " an autoindent (with <<) is two spaces
set expandtab " use spaces, not tabs
set smarttab " use shiftwidth/tabstop based on context

"Show line number
set number

"Show at least 4 lines above or below cursor
set scrolloff=4

" When vimrc is edited, reload it
autocmd! bufwritepost vimrc source ~/.vimrc

"Higlight current line only in insert mode
autocmd InsertLeave * set nocursorline
autocmd InsertEnter * set cursorline

"Highlight cursor
highlight CursorLine ctermbg=8 cterm=NONE


"Set colorscheme
set t_Co=16
set background=dark
"let g:solarized_termcolors=256
colorscheme solarized


" Set linenumber absolute, relative or off
map <leader>na :set number!<CR>
map <leader>nr :set relativenumber!<CR>

set tags=~/.vimtags
set tags=./tags,tags

" incremental search
set incsearch

" show matching brackets in per files
autocmd FileType perl set showmatch

" make tab in v mode ident code
vmap <tab> >gv
vmap <s-tab> <gv

" make tab in normal mode ident code
nmap <tab> I<tab><esc>
nmap <s-tab> ^i<bs><esc>

" remove all trailing whitespaces on file save
autocmd BufWritePre * %s/\s\+$//e

" Use ctrl-[hjkl] to select the active split!
 nmap <leader>k <c-w>k
 nmap <leader>j <c-w>j
 nmap <leader>h <c-w>h
 nmap <leader>l <c-w>l
 nmap <leader>m <c-w>_<c-w>\|
 nmap <leader>= <c-w>=
